name: Hadolint

on: push

jobs:
  RunHadolint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      run: |
          docker run -v"$(pwd):/mnt" -w/mnt -i hadolint/hadolint:v1.23.0 hadolint Dockerfile
